export const workOuts = [
  // {
  //   active: false,
  //   id: 0,
  //   name: "All Lower",
  //   slug: "all_lower",
  //   // exercice: "quadriceps, hamstrings, gluteus, calf, adductors, abductors",
  // },
  // {
  //   active: false,
  //   id: 1,
  //   name: "All Upper",
  //   slug: "all_upper",
  //   // exercice: "back, chest, shoulders, biceps, triceps, forearms, neck",
  // },
  {
    active: false,
    id: 2,
    name: "Abductors",
    slug: "abductors",
    exercice: "abductors",
  },
  {
    active: false,
    id: 3,
    name: "Abs",
    slug: "abs",
    exercice: "abdominal",
  },
  {
    active: false,
    id: 4,
    name: "Adductors",
    slug: "adductors",
    exercice: "adductors",
  },
  {
    active: false,
    id: 5,
    name: "Back",
    slug: "back",
    exercice:
      "latissimus dorsi, serratus anterior, trapezius, external oblique, erector spinae",
  },
  {
    active: false,
    id: 6,
    name: "Lower Back",
    slug: "back_lower",
    exercice: "erector spinae",
  },
  {
    active: false,
    id: 7,
    name: "Upper Back",
    slug: "back_upper",
    exercice: "latissimus dorsi, trapezius, rhomboids",
  },
  {
    active: false,
    id: 8,
    name: "Biceps",
    slug: "biceps",
    exercice: "biceps, brachioradialis",
  },
  {
    active: false,
    id: 9,
    name: "Calfs",
    slug: "calfs",
    exercice: "gastrocnemius, soleus",
  },
  {
    active: false,
    id: 10,
    name: "Chest",
    slug: "chest",
    exercice: "pectoralis major",
  },
  // {
  //   active: false,
  //   id: 11,
  //   name: "Core",
  //   slug: "core",
  //   exercice: "abdominal, obliques, erector spinae",
  // },
  {
    active: false,
    id: 12,
    name: "Lower Core",
    slug: "core_lower",
    exercice: "abdominal, obliques",
  },
  {
    active: false,
    id: 13,
    name: "Upper Core",
    slug: "core_upper",
    exercice: "erector spinae",
  },
  {
    active: false,
    id: 14,
    name: "Forearms",
    slug: "forearms",
    exercice: "brachioradialis, finger extensors, finger flexors",
  },
  {
    active: false,
    id: 15,
    name: "Gluteus",
    slug: "gluteus",
    exercice: "gluteus medius, gluteus maximus",
  },
  {
    active: false,
    id: 16,
    name: "Hamstring",
    slug: "hamstring",
    exercice: "hamstrings",
  },
  {
    active: false,
    id: 17,
    name: "Hands",
    slug: "hands",
    exercice: "finger extensors, finger flexors",
  },
  {
    active: false,
    id: 18,
    name: "Latissimus",
    slug: "latissimus",
    exercice: "latissimus dorsi",
  },
  {
    active: false,
    id: 19,
    name: "Legs",
    slug: "legs",
    exercice: "quadriceps, hamstrings, adductors, abductors, calf",
  },
  { active: false, id: 21, name: "Neck", slug: "neck", exercice: "Trapezius" },
  {
    active: false,
    id: 22,
    name: "Quadriceps",
    slug: "quadriceps",
    exercice: "Quadriceps",
  },
  {
    active: false,
    id: 23,
    name: "Shoulders",
    slug: "shoulders",
    exercice: "Deltoid",
  },
  // {
  //   active: false,
  //   id: 24,
  //   name: "Back Shoulders",
  //   slug: "shoulders_back",
  //   exercice: "Trapezius, Deltoid, Rotator Cuff",
  // },
  // {
  //   active: false,
  //   id: 25,
  //   name: "Front Shoulders",
  //   slug: "shoulders_front",
  //   exercice: "Deltoid, Pectoralis Major",
  // },
  {
    active: false,
    id: 26,
    name: "Triceps",
    slug: "triceps",
    exercice: "Triceps",
  },
];

export const LocationsName = [
  {
    active: false,
    locationId: 0,
    locationName: "Home",
    locationSlug: "home",
  },
  {
    active: false,
    locationId: 1,
    locationName: "Gym",
    locationSlug: "gym",
  },
  {
    active: false,
    locationId: 2,
    locationName: "Park",
    locationSlug: "park",
  },
]

