

export const workOut = [
  { active: false, id: 1, name: "All", slug: "all" },
  { active: false, id: 2, name: "All Lower", slug: "all_lower" },
  { active: false, id: 3, name: "All Upper", slug: "all_upper" },
  { active: false, id: 4, name: "Abductors", slug: "abductors" },
  { active: false, id: 5, name: "Abs", slug: "abs" },
  { active: false, id: 6, name: "Adductors", slug: "adductors" },
  { active: false, id: 7, name: "Back", slug: "back" },
  { active: false, id: 8, name: "Lower Back", slug: "back_lower" },
  { active: false, id: 9, name: "Upper Back", slug: "back_upper" },
  { active: false, id: 10, name: "Biceps", slug: "biceps" },
  { active: false, id: 11, name: "Calfs", slug: "calfs" },
  { active: false, id: 12, name: "Chest", slug: "chest" },
  { active: false, id: 13, name: "Core", slug: "core" },
  { active: false, id: 14, name: "Lower Core", slug: "core_lower" },
  { active: false, id: 15, name: "Upper Core", slug: "core_upper" },
  { active: false, id: 16, name: "Forearms", slug: "forearms" },
  { active: false, id: 17, name: "Gluteus", slug: "gluteus" },
  { active: false, id: 18, name: "Hamstring", slug: "hamstring" },
  { active: false, id: 19, name: "Hands", slug: "hands" },
  { active: false, id: 20, name: "Latissimus", slug: "latissimus" },
  { active: false, id: 21, name: "Legs", slug: "legs" },
  { active: false, id: 22, name: "Neck", slug: "neck" },
  { active: false, id: 23, name: "Quadriceps", slug: "quadriceps" },
  { active: false, id: 24, name: "Shoulders", slug: "shoulders" },
  { active: false, id: 25, name: "Back Shoulders", slug: "shoulders_back" },
  { active: false, id: 26, name: "Front Shoulders", slug: "shoulders_front" },
  { active: false, id: 27, name: "Triceps", slug: "triceps" },
];
